blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ General Questions | Ø³ÙˆØ§Ù„Ø§Øª Ø¹Ù…ÙˆÙ…ÛŒ
    url: https://github.com/saeed-dev/pywarp/discussions
    about: For help, troubleshooting, or general discussion | Ø¨Ø±Ø§ÛŒ Ú©Ù…Ú©ØŒ Ø±ÙØ¹ Ø§Ø´Ú©Ø§Ù„ ÛŒØ§ Ø¨Ø­Ø« Ø¹Ù…ÙˆÙ…ÛŒ
